database:
  driverClass: org.postgresql.Driver
  user: accountsdb
  password: accountsdb
  url: jdbc:postgresql://localhost/accountsdb
  minSize: 1

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
  requestLog:
    appenders: []    

#assets:
# overrides:
#   /assets: some_ui/src/main/webapp/assets/
        
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO    
    org.hibernate.SQL: INFO
    com.sun.jersey.api.container.filter.LoggingFilter: WARN
  appenders:
    - type: console

refdata: refdata

modelResource: accounts-model.xml
   
beanValidationConstraints: constraints.xml

swagger:
  resourcePackage: com.thesett.accounts.services
